name = "LightSumTypes"
uuid = "f56206fc-af4c-5561-a72a-43fe2ca5a923"
version = "4.0.2"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1.2"
ExprTools = "0.1"
MacroTools = "0.5"
PrecompileTools = "1"
